name: AzureResumeStatic

on:
    push:
        branches: [ main]
    pull_request:
        branches: [ main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:            
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURERESUMECREDS }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
            az storage blob upload-batch --account-name azureresume173 -d '$web' -s .
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name "CDNazureresume" --name "https://azureresume173.z33.web.core.windows.net" --resource-group "rg-azureresume"

  # Azure logout 
    - name: logout
      run: |
            az logout

